def get_metric_labels():
    return {
        'affordability_ratio':'Affordability Ratio',
        'appeal_index':'Appeal Index',
        'crimes_against_persons_rate':'Crimes Against Persons Rate',
        'crimes_against_property_rate':'Crimes Against Property Rate',
        'crimes_against_society_rate':'Crimes Against Society Rate',
        'economic_diversity_index':'Economic Diversity Index',
        'est_number_of_jobs':'Estimated Number of Jobs',
        'higher_education': '% Population with Higher Education',
        'home_valuation_status':'Home Price Valuation',
        'income_growth_rate': 'Income Growth Rate',
        'mean_education_rating':'Mean GreatSchools.org Rating',
        'mean_travel_time_to_work':'Mean Commute Time (min)',
        'median_age':'Median Age',
        'median_income':'Median Individual Income',
        'median_income_families':'Median Household Income',
        'median_monthly_housing_cost':'Median Monthly Housing Cost',
        'median_real_estate_taxes':'Median Real Estate Taxes',
        'owner_renter_ratio':'Owner Renter Ratio',
        'pct_higher_education':'% Adults with Higher Education',
        'pct_middle_aged_adults':'% Adults over 30?',
        'pct_young_adults':'% Adjusts under 30?',
        'total_crime_rate':'Total Crime Rate (per cap)',
        'total_working_age_population':'Population (Working Age)',
        'zhvi':'Zillow Home Value Index'
    }